# Generated by Django 4.2 on 2024-07-10 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_cult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cult',
            old_name='name',
            new_name='theme',
        ),
    ]
