# Generated by Django 4.2 on 2024-07-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_alter_cult_date'),
        ('church', '0003_rename_name_cult_theme'),
    ]

    operations = [
    ]
