# Generated by Django 4.2 on 2024-07-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_merge_20240720_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cult',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
