# Generated by Django 4.2 on 2024-07-20 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_playlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
