# Generated by Django 4.2 on 2024-07-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_playlist_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='versionmusic',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='category',
            field=models.ManyToManyField(to='music.musiccategory'),
        ),
    ]
