# Generated by Django 4.2 on 2024-07-10 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0002_cult'),
        ('music', '0002_remove_music_music_chord_alter_versionmusic_music_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionPraise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MemberPraise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('availability', models.BooleanField(default=True)),
                ('cell_phone', models.CharField(max_length=14)),
                ('is_member', models.BooleanField(default=False)),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_praise_church', to='church.church')),
                ('function', models.ManyToManyField(to='praise.functionpraise')),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cult', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cult_cast', to='church.cult')),
                ('drums', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drums_cast', to='praise.memberpraise')),
                ('electric_guitar', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electric_guitar_cast', to='praise.memberpraise')),
                ('guitar', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guitar_cast', to='praise.memberpraise')),
                ('low', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='low_cast', to='praise.memberpraise')),
                ('musical_keyboard', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musical_keyboard_cast', to='praise.memberpraise')),
                ('playlist', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist_cast', to='music.playlist')),
                ('vocal', models.ManyToManyField(related_name='vocal_cast', to='praise.memberpraise')),
            ],
        ),
    ]
