# Generated by Django 4.2 on 2024-07-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_function_member'),
        ('praise', '0002_function_member_remove_memberpraise_church_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='church',
        ),
        migrations.RemoveField(
            model_name='member',
            name='function',
        ),
        migrations.AlterField(
            model_name='cast',
            name='members',
            field=models.ManyToManyField(to='church.member'),
        ),
        migrations.DeleteModel(
            name='Function',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
